apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ayoub-service-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`localhost`) && PathPrefix(`/ayoub`)
      kind: Rule
      services:
        - name: ayoub-service
          port: 9090
      middlewares:
          # - name: keycloak-jwt-verifier
          #   namespace: default
          # - name: my-jwt-middleware
          #   namespace: default
          - name: jwt-signature-validation
            namespace: default
    - match: PathPrefix(`/token`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
          namespace: default
      middlewares:
        - name: token-rewrite
          namespace: default
    - match: PathPrefix(`/realms/`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080