apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ayoub-service-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`localhost`) && PathPrefix(`/ayoub`)
      kind: Rule
      services:
        - name: ayoub-service
          port: 9090
      middlewares:
        # - name: basic-auth-middleware
        #   namespace: default
        # - name: my-headerauthentication
        #   namespace: default
          # - name: my-traefik-subsonic-basicauth
          #   namespace: default
        # - name: jwt-validator-middleware
        #   namespace: default
          - name: my-jwt-middleware
            namespace: default
          # - name: my-traefik-cluster-ratelimit
          #   namespace: default 
