apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ayoub-service-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ayoub.local`)
      kind: Rule
      services:
        - name: ayoub-service
          port: 9090
      middlewares:
        - name: basic-auth-middleware
          namespace: default
