apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-jwt-middleware
  namespace: default
spec:
  plugin:
    jwt-middleware:
      secret: ThisIsAPresharedSecret

# test : 
# ---- payload----
#  {
#   "sub": "1234567890",
#   "name": "othmane",
#   "iat": 1516239022,
#   "exp": 1738016117
# }

# ----- signature -------
# ThisIsAPresharedSecret
# ----------command---------
# curl -H "Authorization: Bearer <new_token>" http://localhost:81/ayoub/api/v1/users


