apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-jwtvalidator
  namespace: default
spec:
  plugin:
    name: my-jwtvalidator
    config:
      secretKey: "my-dummy-secret-key"  # Replace with your actual secret key
      authHeader: "Authorization"        # The HTTP header containing the token
      algo: "HS256"                      # Algorithm used in the token
