apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: my-keycloakopenid
    namespace: default
spec:
    plugin:
        keycloakopenid:
            ClientID: test-client
            ClientSecret: 4YcdkUM8IY7dsprbQ6k0TrDanVkWu9FH
            KeycloakRealm: master
            KeycloakURL: http://localhost:30094
            Scope: openid
            # TokenCookieName: AUTH_TOKEN
            UseAuthHeader: "false"
