apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: test-account
      containers:
        - name: traefik
          image: traefik:v2.9.6  # Updated to v2.9.6
          args:
            - --api.insecure
            - --providers.kubernetescrd=true
            - --providers.kubernetesingress
            - --entrypoints.web.address=:81
            # - --experimental.plugins.traefik-subsonic-basicauth.modulename=github.com/crazygolem/traefik-subsonic-basicauth
            # - --experimental.plugins.traefik-subsonic-basicauth.version=v0.2.0
            # - --experimental.plugins.headerauthentication.modulename=github.com/omar-shrbajy-arive/headerauthentication
            # - --experimental.plugins.headerauthentication.version=v1.0.3
            - --experimental.plugins.jwt-middleware.modulename=github.com/tpaulus/jwt-middleware
            - --experimental.plugins.jwt-middleware.version=v1.1.13
            # Enable access logs
            - --accesslog=true
            - --accesslog.fields.DefaultMode=keep
            - --log.level=DEBUG
            # Enable Prometheus metrics
            - --metrics.prometheus=true
            - --metrics.prometheus.addentrypointslabels=true
            #rate limiter
            # - --experimental.plugins.traefik-cluster-ratelimit.modulename=github.com/nzin/traefik-cluster-ratelimit
            # - --experimental.plugins.traefik-cluster-ratelimit.version=v1.1.1
          ports:
            - name: web
              containerPort: 81
            - name: dashboard
              containerPort: 8080
