apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: test-account
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - --api.insecure
            - --providers.kubernetescrd=true
            - --providers.kubernetesingress
            - --entrypoints.web.address=:81
            - --metrics.datadog.addentrypointslabels
            - --tracing
            - --accesslog
            
          ports:
            - name: web
              containerPort: 81
            - name: dashboard
              containerPort: 8080
